---
- hosts: node1
  become: true
  tasks:

    - name: "rhel10-unit-systemd : dnf install LAMP packages"
      ansible.builtin.dnf: 
        name: httpd,mariadb,mariadb-server 
        state: installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "rhel10-unit-systemd : workshop script installs"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'workshop-checkhost.j2',           dest: '/usr/local/bin/workshop-systemd-checkhost.sh'}
        - {src: 'workshop-systemd-lamp.j2',        dest: '/usr/local/bin/workshop-systemd-lamp.sh'}
        - {src: 'workshop-systemd-httpdconfig.j2', dest: '/usr/local/bin/workshop-systemd-httpdconfig.sh'}
