---
- hosts: node2
  become: true
  tasks:

    - name: "rhel10-unit-nftables : dnf install firewalld"
      ansible.builtin.dnf: 
        name: firewalld,nftables
        state: installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    ##    NOTE:
    ##
    ##         You should NOT have both nftables
    ##         and firewalld services enabled.
    ##

    - name: "rhel10-unit-nftables : service start/enable/unmask nftables"
      ansible.builtin.systemd_service:
        name: nftables 
        state: restarted
        enabled: yes 
        masked: no

    - name: "rhel10-unit-nftables : service stop/disable/mask firewalld"
      ansible.builtin.systemd_service:
        name: firewalld 
        state: stopped
        enabled: no
        masked: yes
  
    - name: "rhel10-unit-nftables : workshop script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'workshop-checkhost.j2',               dest: '/usr/local/bin/workshop-nftables-checkhost.sh'}
