---
- hosts: leapp
  become: true
  tasks:
  
    - name: "rhel10-unit-leapp : dnf install leapp upgrade, cockpit, cockpit-leapp"
      ansible.builtin.dnf: 
        name: leapp-upgrade,cockpit,cockpit-leapp
        state: installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5
 
    - name: "rhel10-unit-leapp : calculate required /boot disk constipation factor"
      shell:
        cmd: |
            FS_TOTAL=`df --output=size -B 256  /boot | sed 1d`; 
            FS_USED=`df --output=used -B 256  /boot | sed 1d`; 
            echo "$(( ( $FS_TOTAL * 95 / 100 ) - $FS_USED ))"
      register: disk_pressure

    - name: "rhel10-unit-leapp : result of disk pressure analysis" 
      debug: 
        msg: "Calculus results reveal we need to add {{ disk_pressure.stdout }} 256k blocks of garbage"

    - name: "rhel10-unit-leapp : create massive dump to act as Leapp Pre-Upgrade Inhibitor"
      ansible.builtin.command: dd if=/dev/zero of=/boot/bigfile bs=256 count={{ disk_pressure.stdout }}

    - name: "rhel10-unit-leapp : workshop file installs"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'workshop-checkhost.j2', dest: '/usr/local/bin/workshop-leapp-checkhost.sh'} 
