#---

- hosts: myBastion
  become: true
  tasks:

    - name: "rhel10-showroom: install required packages"
      dnf:
        name: git,podman
        state: installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "rhel10-showroom: kill any running containers of antora"
      ansible.builtin.shell:
        cmd: |
          if podman ps --noheading | grep antora; then
            podman kill antora
          fi

    - name: "rhel10-showroom: wait for running containers of antora to die and cleanup"
      ansible.builtin.shell:
        cmd: |
          if podman ps --noheading | grep antora; then
            echo "wait"
          fi
      register: antora_result
      until: antora_result.stdout != "wait"
      retries: 12
      delay: 5

    - name: "rhel10-showroom: clone/update the showroom git repo"
      ansible.builtin.git:
        repo: "https://github.com/rhpds/hol-rhel10-showroom"
        dest: "~root/rhel10-workshop-showroom"
        version: "development"
        clone: yes
        update: true

    - name: "rhel10-showroom: run the showroom pod on port 8080"
      ansible.builtin.shell:
        chdir: "~root/rhel10-workshop-showroom"
        cmd: |
          podman run -d --rm --name antora -v $PWD:/antora:z -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer

