---
- hosts: leapp
  become: true
  tasks:
  
#    - name: "rhel10-unit-leapp : dnf install firewalld"
#      ansible.builtin.dnf: 
#        name: firewalld 
#        state: installed
#      register: result
#      retries: 10
#      until: result is succeeded
#      delay: 5

#    - name: "rhel10-unit-leapp : data file installs"
#      vars:
#        t_filename: "leapp-data17.tar.gz"
#        t_destpath: "/usr/local/src"
#        t_src_url:  "https://people.redhat.com/cdoerbec/VQRlX6Ggks"
#      ansible.builtin.get_url:
#        url: "{{ t_src_url }}/{{ t_filename }}"
#        dest: "{{ t_destpath }}/{{ t_filename }}"
#        owner: root
#        group: root
#        mode: "0644"
#        timeout: 60
#        force: no
#      register: leapp_download
#      until: leapp_download is not failed
#      retries: 5
#      ignore_errors: yes

  tasks:
    - name: "rhel10-unit-leapp : Create bigfile in /boot so there's an inhibitor"
      ansible.builtin.command: dd if=/dev/zero of=/boot/bigfile bs=1024 count=450000
#      changed_when: false
      
    - name: "rhel10-unit-leapp : workshop file installs"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'workshop-checkhost.j2', dest: '/usr/local/bin/workshop-leapp-checkhost.sh'} 
