---
- hosts: myBastion
  become: true
  tasks:

    - name: "rhel10-unit-imagebuilder : yum install packages"
      yum: name=osbuild-composer,composer-cli,cockpit-composer,guestfs-tools,libguestfs-tools state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "rhel10-unit-imagebuilder : create repo override directory"
      file:
        path: "/etc/osbuild-composer/repositories"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: "rhel10-unit-imagebuilder : workshop script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - {mode: '0644', src: 'lib-exercise.j2',             dest: '/usr/local/bin/lib-exercise.sh'}
        - {mode: '0744', src: 'lib-exercise-test.j2',        dest: '/usr/local/bin/lib-exercise-test.sh'}
        - {mode: '0744', src: 'workshop-checkhost.j2',       dest: '/usr/local/bin/workshop-imagebuilder-checkhost.sh'}
        - {mode: '0744', src: 'workshop-osbuild-config.j2',  dest: '/usr/local/bin/workshop-imagebuilder-config.sh'}
        - {mode: '0744', src: 'workshop-osbuild-toml.j2',    dest: '/usr/local/etc/imagebuilder-sample.toml'}
        - {mode: '0744', src: 'workshop-osbuild-html.j2',    dest: '/usr/local/etc/index.html'}

    - name: "rhel10-unit-imagebuilder : service stop"
      service: 
        name: "osbuild-composer.socket" 
        enabled: yes
        state: stopped

    - name: "rhel10-unit-imagebuilder : service workers stop"
      service: 
        name: "{{ item }}"
        state: stopped
      with_items:
        - "osbuild-worker@.service.d"
        - "osbuild-worker@1.service"
        - "osbuild-composer.service"

    - name: "rhel10-unit-imagebuilder : service enable and start"
      service: 
        name: "osbuild-composer.socket" 
        enabled: yes
        state: started

